<<<<<<< HEAD
# Generated by Django 5.1 on 2024-08-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
=======
# Generated by Django 5.1 on 2024-08-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
>>>>>>> 2c9025f (Initial commit with requirements.txt)
