# Generated by Django 5.1.1 on 2024-10-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedaddress',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
