# Generated by Django 5.1.1 on 2024-10-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_savedaddress_city_alter_savedaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedaddress',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
    ]
