# Generated by Django 5.1.1 on 2024-10-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_savedaddress_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaddress',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
